project:
  type: website
  output-dir: _site

website:
  title: "MOSAiC"
  site-url: https://urol-e5.github.io/MOSAiC/
  navbar:
    logo: img/sm_logo.png
  #   left:
  #     - text: Home
  #       href: index.qmd
  #     - text: Data Files
  #       href: data.qmd
  #     - text: JBrowse
  #       href: https://gannet.fish.washington.edu/e5-mosaic
        
        
  sidebar:
    style: "docked"        # or "floating"
    search: true
    collapse-level: 2
    contents:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd        
      - section: "Data Files"
        contents:
          - text: "Expression Values"
            href: counts.qmd
          - text: "Genome Features"
            href: features.qmd
      - text: Genome Browser
        file: jbrowse.qmd

    tools:
      - icon: github
        href: https://github.com/urol-e5/MOSAiC
        
        
  page-footer:
    left: "Supported by NSF [disclaimer](disclaimer.qmd)"
    right: "Built with Quarto"

format:
  html:
    theme:
      light: flatly
      dark: cyborg

filters:
  - filters/list-data.lua

metadata:
  repo-url: https://github.com/urol-e5/MOSAiC
  repo-actions: [source]
